# @var rke_user: rke
# User that will be used to connect on nodes during the installation proccess.
rke_user: vagrant
network_interface: eth0
rke_kubernetes_version: v1.19.3-rancher1-1
rke_version: v1.2.1
rke_binary_url: "https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64"
# @var rke_node: "{{ groups['masters'] | first }}"
# Node that will be used to deploy cluster using RKE.
rke_node: "{{ groups['masters'] | first }}"
rke_ignore_docker_version: true
rke_addon_job_timeout: 60
# @var rke_cluster_network_cidr: '10.42.0.0/16'
# CIDR pool used to assign IP addresses to pods in the cluster.
rke_cluster_network_cidr: 10.42.0.0/16
# @var rke_service_network_cidr: '10.43.0.0/16'
# This is the virtual IP address that will be assigned to services created on Kubernetes.
rke_service_network_cidr: 10.43.0.0/16
rke_node_groups:
  - name: masters
    role:
      - controlplane
  - name: workers
    role:
      - worker